language: generic

sudo: required

services:
  - docker

bundler_args: --retry 5

install: travis_retry pip install alpine

before_install:
  - docker build -t bale/react-test-app -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true bale/react-test-app npm run test

after_success:
  - docker build -t bale/docker-frontend ./frontend
  - docker build -t bale/docker-backend ./backend
  - docker build -t bale/docker-nginx ./nginx
  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin
  - docker push bale/docker-frontend
  - docker push bale/docker-backend
  - docker push bale/docker-nginx